Basic OOP class setup from CRC cards
CMPUT301W22T20/QR-Score pull request #30
Opened 2022-02-28 02:16 UTC by mlam7

Here is the setup I've made for a number of the class files we'll need, taken from the CRC cards. I've commented out some of the things that I don't think are directly related to my user stories, but have them there so they can be implemented later.

2022-02-28 03:55 UTC, liu-william commented on app/src/main/java/com/example/qrscore/Account.java
> +    public void addQRCode(QRCode toAdd) {
Instead of toAdd as the param name, I feel like we should just leave it as qrCode for consistency. As we know this method is used to add a qrCode.

2022-02-28 03:57 UTC, liu-william commented on app/src/main/java/com/example/qrscore/Account.java
> +    public void removeQRCode(QRCode toRemove) {
Similar to addQRCode, feel like should just name it qrCode

2022-02-28 03:57 UTC, liu-william commented on app/src/main/java/com/example/qrscore/Score.java
> +package com.example.qrscore;
For Score.java, we should probably name it QRScore.java as there are scores for both players and QR codes

2022-03-03 20:21 UTC, akaujla commented
Everything looks good to me except just add some javadocs for the classes and public methods

2022-03-05 19:21 UTC, mjbraun95 requested changes

2022-03-07 17:37 UTC, merged